name: Test ARM64
permissions: read-all
on: [push, pull_request]
jobs:
  run:
    uses: ./.github/workflows/test_template.yaml
    with:
      runs-on: actuated-arm64-8cpu-8gb
      targets: "['linux-arm64-unit-test-4-cpu-race']"
