name: Test
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19.3"
      # TODO(ahrtr): add test matrix for different platform and ARCH
      - run: make test

