name: Test AMD64
permissions: read-all
on: [push, pull_request]
jobs: 
  test-linux-amd64:
    uses: ./.github/workflows/test_template.yaml
    with:
      targets: "['linux-amd64-unit-4-cpu-race']"
  test-linux-386:
    uses: ./.github/workflows/test_template.yaml
    with:
      targets: "['linux-386-unit-1-cpu']"
